language: php
php:
  - '5.6'
  - '7.1'
sudo: required
dist: trusty
group: edge


before_install:
  - uname -a
  - php --version
  - phpunit --version
install:
  - composer install -d app-api
  - composer dump-autoload -o -d app-api
before_script:
  - cd app-api
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
