language: php
php:
  - '5.6'
  - '7.1'
sudo: required
dist: trusty
group: edge


before_install:
  - uname -a
  - php --version
  - phpunit --version
install:
  - composer install -d app-api
  - composer dump-autoload -o -d app-api
script:
  - app-api/vendor/bin/phpunit

notifications:
  email: true